### ISSUE TITLE
gapi.auth.getToken() is null

### ISSUE THREAD

**Issue by sratatata** [canemacchina/angular-google-client#2]
When im trying to get 

``` javascript

googleClient.afterApiLoaded().then(function () {
   ...
  if(gapi.auth.getToken() !== null){
      // if token exists, send access token in request
      request.setRequestHeader('Authorization','Bearer ' + gapi.auth.getToken().access_token);
  }
   ...
}

```

Token is always null. I've no idea how to make it working. It was working when I was using gapi directly in non angular project.
It's a bug or feature?

**Comment by canemacchina** [comment]
Are you sure?
I've tried your piece of code, and in my Case gapi.auth.getToken() is not null.
Could you provide me a "working" example that has that problem?
Thanks

**Comment by canemacchina** [comment]
To be more precise: `gapi.auth.getToken()` should never return null (and this is a Google library feature, not mine). If the user is not logged in, `gapi.auth.getToken()`return an empty object. Is the user is logged in, it contains token information.
In the case of my library, the only thing that differ from gapi standard library is that I don't use  `gapi.auth.authorize` to log in the user, but instead I use Google Sign in button, that use its own method.
To authorize also gapi, what I do is `gapi.auth.setToken(googleUser.getAuthResponse())` (`googleUser.getAuthResponse()` return the same object of `gapi.auth.getToken()`) in a signin listener function of Google Sign in button, so the object returned by `gapi.auth.getToken()` should be correct if the user is logged in.
Check [google-sign-in.directive.js](https://github.com/canemacchina/angular-google-client/blob/master/src/directives/google-sign-in.directive.js)

**Comment by sratatata** [comment]
Hey... It would be hard to provide working example. However I've noticed and solved my problem using this: 

```
gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().access_token
```

I would check code again and maybe do some working example during the weekend..

**Comment by canemacchina** [comment]
Seems strange, because  `gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().access_token` is, as a matter of fact, what I pass to `gapi.auth.setToken`. To be precise, i do `gapi.auth.setToken(googleUser.getAuthResponse());` and `googleUser`, in that case, is the same object returned by  `gapi.auth2.getAuthInstance().currentUser.get()`.

If you want, I can provide to you a working example...

**Comment by sratatata** [comment]
I think that I would live it as it is. Works! Thats most important:)

**Comment by paulzmuda** [comment]
In working on my own JS client I ran into the same issue from one of Google's sets of sample code:

`gapi.auth2.getAuthInstance().currentUser.get().getAuthResponse().access_token`

is what did it for mine too.  Thank you @sratatata for updating with what worked for you.

**Comment by canemacchina** [comment]
Could you provide me your `googleClientProvider` configuration?
I think is a problem related to a bug I've discovered long time ago into the Google Client Library.
