### ISSUE TITLE
Login Required after making an API Call

### ISSUE THREAD

**Issue by arielcr** [canemacchina/angular-google-client#3]
Great module!

But I get a "Login Required" message after making an Admin Directory API Call. I don't know if there is a way to log in automatically, and if the user has not grant any permission, display the Google Login Form.

What I'm missing?

Thanks!

**Comment by canemacchina** [comment]
Hi! First of all, thanks!

Maybe you forgot to authenticate the user? Check [User authentication & authorization](https://github.com/canemacchina/angular-google-client#user-authentication--authorization) on the Readme file.
Google Sign-in button should authenticate automatically the user (if the user was previously authenticated on your app...)

Tell me if you have any kind of problem.

**Comment by arielcr** [comment]
Thanks for your reply!

Is there a way to avoid using the sign in button, or to call a function that fires up the authentication? I'm building a CMS from which you can add emails to your Google Admin Directory, so I want to be able to click on a "Add Email" button, without previously authentication (I know I have to authenticate, but I want to just check if the user is authenticated, and if not, pop up the Google Authentication form)

I don't know if it's clear for you...

Thanks again for your help!

**Comment by canemacchina** [comment]
Ah ok, I've understand. I think is possible, using gapi authentication
instead of sign-in button.

Mmmh,  I can consider to implement, into the provider, the ability to
choose between using sign-in button or standard gapi auth method. Let me
think how I could do it...
Il 08 mar 2016 2:45 PM, "Ariel Orozco" notifications@github.com ha
scritto:

**Comment by arielcr** [comment]
Great! Thanks for your help!
