### ISSUE TITLE
How can i inject Bearer at http header before request be sent?

### ISSUE THREAD

**Issue by axacheng** [canemacchina/angular-google-client#4]
As subject. I thought $httpProvider.interceptors can be automatically injected my jwt token to  googleClient (or cmGoogleApi ), but it actually didn't. While I switch to $http I can get **authorization: Bearer** eyJxxxxxx . and everything works great.

Does angular-google-client allow us to inject jwt token by using $httpProvider.interceptors.push or any other similar approach?

Thanks

**Comment by canemacchina** [comment]
No, this library is a simple wrapper for the official [Google Client Library for Javascript](https://developers.google.com/api-client-library/javascript/start/start-js), and the Google Library uses its own objects to communicate with the remotes services. So you cannot use Anguar $http interceptor, sorry

EDIT:
Re reading your post I have had a doubt: are you asking me how to inject a valid token into my library, without need to authenticate the user?
Well, if you have an Oauth2 valid token to inject, you can try to inject it directly into gapi object:

`googleClient.afterScriptsLoaded().then(function(){
    gapi.auth.setToken(<your token here>);
});`

I think is possible (and if you see the [source code](https://github.com/canemacchina/angular-google-client/blob/master/src/directives/google-sign-in.directive.js#L19), i do this thing when the user log in)

**Comment by axacheng** [comment]
Thank you Lorenzo.

I looked up gapi in deep and found a workaround to inject authentication in the header.
Just simply to use **gapi.auth.setToken** method In index.html it'd attach **Bearer** jwt in every requests. Hopefully, that helps to others.  ;)

EDIT:
Correct me if I'm wrong. I think the easier way to inject token is calling gapi.auth.setToken in index.html, rather than putting gapi.auth.setToken on each googleClient.afterApiLoaded calls.

``` javascript
index.html
    <script src="https://apis.google.com/js/api.js"></script>
    <script>
      function onLoadFn() {
        var access_key = localStorage.getItem('access_key')
        gapi.auth.setToken({
          access_token: access_key
        })
      }
      gapi.load("client", onLoadFn);
    </script>
```

**Comment by canemacchina** [comment]
Just one thing: if you are using my library, don't forget to set the token inside `afterScriptsLoaded` method, as I told you in the previous comment, to be sure to have gapi correctly loaded.
Bye bye!
